using ReportGen.Tools.DAL;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Word = Microsoft.Office.Interop.Word;

namespace ReportGen.Tools
{
    public class Extentions
    {

        private UnitOfWork _unitOfWork = new UnitOfWork();

        //http://stackoverflow.com/questions/21833102/vsto-addin-text-content-control
        public void InsertIntoBookmark(Microsoft.Office.Interop.Word.Document Document, string bookmarkName, string bookMarkTypeId, string text)
        {
            if (Document != null && Document.Bookmarks.Exists(bookmarkName))
            {
                var range = Document.Bookmarks[bookmarkName].Range;
                Document.Bookmarks[bookmarkName].Delete();
                range.Text = text;
                range.Font.Shading.BackgroundPatternColor = Word.WdColor.wdColorDarkGreen;
                
                

                // replace bookmark
                Document.Bookmarks.Add(bookmarkName, range);
                


            }
            else
            {
                Word.Selection selection = Globals.ThisAddIn.Application.Selection;
                if (selection != null && selection.Range != null)
                {
                    var vstoDocument = Globals.Factory.GetVstoObject(Document);
                    var firstParagraph = vstoDocument.Controls.AddBookmark(selection.Range, bookmarkName);
                    var range = Document.Bookmarks[bookmarkName].Range;
                    range.Font.Shading.BackgroundPatternColor = Word.WdColor.wdColorDarkGreen;

                    if ((_unitOfWork.BookMarkRepository.FindBy(id => id.BookmarkName == bookmarkName)) == null)
                    {
                        _unitOfWork.BookMarkRepository.Add(new Models.BookMark { BookMarkID = Guid.NewGuid().ToString("D"), BookmarkName = bookmarkName, BookMarkTypeID = bookMarkTypeId });

                    }
                } 
            }
            Document.Save();
            _unitOfWork.Save();
            //CreateTemplatedDocuments(Document);
        }



        //http://stackoverflow.com/questions/161356/create-a-new-word-document-using-vsto
        public void CreateTemplatedDocuments(Microsoft.Office.Interop.Word.Document Document, ICollection<string> data)
        {
            //var temp = Globals.ThisAddIn.Application.Templates;

            foreach (var i in data)
            {
                var doc = Globals.ThisAddIn.Application.Documents.Add(Document.FullName);
                //Globals.ThisAddIn.documentOpenEvent(doc);

                Word.Document thisDoc = this.ApplyData(doc, i);








                string desktopFolder = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
                string filename = i + ".docx";

                thisDoc.SaveAs2(Path.Combine(desktopFolder, "autogenerated", filename));
                thisDoc.Close(); 
            }
        }

        private Word.Document ApplyData(Word.Document doc, string i)
        {
            //var data = _unitOfWork.BookMarkRepository.FindBy(id => id.BookMarkID == i);
            
            //if (doc.Bookmarks.Exists("maintitle"))
            //{
            //    var range = doc.Bookmarks["maintitle"].Range;
            //    doc.Bookmarks["maintitle"].Delete();
            //    range.Text = i;
            //    range.Font.Shading.BackgroundPatternColor = Word.WdColor.wdColorAutomatic;
               
            //}


            foreach(var bm in doc.Bookmarks)
            {
                var range = doc.Bookmarks[bm].Range;
                doc.Bookmarks[bm].Delete();
                range.Text = i;
                range.Font.Shading.BackgroundPatternColor = Word.WdColor.wdColorAutomatic;
            }






            return doc;
        }
    }
}
