using ReportGen.Tools.DAL;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Word = Microsoft.Office.Interop.Word;

namespace ReportGen.Tools
{
    public class Extentions
    {

        private UnitOfWork _unitOfWork = new UnitOfWork();

        //http://stackoverflow.com/questions/21833102/vsto-addin-text-content-control
        public void InsertIntoBookmark(Microsoft.Office.Interop.Word.Document Document, string bookmarkName, string bookMarkTypeId, string text)
        {
            if (Document != null && Document.Bookmarks.Exists(bookmarkName))
            {
                var range = Document.Bookmarks[bookmarkName].Range;
                Document.Bookmarks[bookmarkName].Delete();
                range.Text = text;
                range.Font.Shading.BackgroundPatternColor = Word.WdColor.wdColorDarkGreen;
                
                

                // replace bookmark
                Document.Bookmarks.Add(bookmarkName, range);
                


            }
            else
            {
                Word.Selection selection = Globals.ThisAddIn.Application.Selection;
                if (selection != null && selection.Range != null)
                {
                    var vstoDocument = Globals.Factory.GetVstoObject(Document);
                    var firstParagraph = vstoDocument.Controls.AddBookmark(selection.Range, bookmarkName);
                    var range = Document.Bookmarks[bookmarkName].Range;
                    range.Font.Shading.BackgroundPatternColor = Word.WdColor.wdColorDarkGreen;

                    if ((_unitOfWork.BookMarkRepository.FindBy(id => id.BookmarkName == bookmarkName)) == null)
                    {
                        _unitOfWork.BookMarkRepository.Add(new Models.BookMark { BookMarkID = Guid.NewGuid().ToString("D"), BookmarkName = bookmarkName, BookMarkTypeID = bookMarkTypeId });

                    }
                } 
            }
            Document.Save();
            _unitOfWork.Save();
            //CreateTemplatedDocuments(Document);
        }



        //http://stackoverflow.com/questions/161356/create-a-new-word-document-using-vsto
        public void CreateTemplatedDocuments(Microsoft.Office.Interop.Word.Document Document, ICollection<string> data)
        {
            //var temp = Globals.ThisAddIn.Application.Templates;

            foreach (var i in data)
            {
                var doc = Globals.ThisAddIn.Application.Documents.Add(Document.FullName);



                doc.Paragraphs[1].Range.InsertParagraphBefore();
                doc.Paragraphs[1].Range.Text = "This text was added by using code.";








                string desktopFolder = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
                string filename = i + ".docx";

                doc.SaveAs2(Path.Combine(desktopFolder, "autogenerated", filename));
                doc.Close(); 
            }
        }

        
    }
}
